// <auto-generated />
using EFD2.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EFD2.Migrations
{
    [DbContext(typeof(ITIContext))]
    [Migration("20250122102953_v14")]
    partial class v14
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EFD2.Models.Department", b =>
                {
                    b.Property<int>("deptid")
                        .HasColumnType("int");

                    b.Property<string>("location")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("deptid");

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            deptid = 1,
                            location = "lec1",
                            name = "dotnet"
                        },
                        new
                        {
                            deptid = 2,
                            location = "lec2",
                            name = "php"
                        },
                        new
                        {
                            deptid = 3,
                            location = "lec3",
                            name = "front"
                        });
                });

            modelBuilder.Entity("EFD2.Models.Employee", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("age")
                        .HasColumnType("int")
                        .HasColumnName("employeeage");

                    b.Property<int>("did")
                        .HasColumnType("int");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("salary")
                        .HasColumnType("money");

                    b.HasKey("id");

                    b.HasIndex("did");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("EFD2.Models.Project", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("duration")
                        .HasColumnType("int");

                    b.Property<string>("location")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("EFD2.Models.empProj", b =>
                {
                    b.Property<int>("empid")
                        .HasColumnType("int");

                    b.Property<int>("projid")
                        .HasColumnType("int");

                    b.HasKey("empid", "projid");

                    b.HasIndex("projid");

                    b.ToTable("EmpProjs");
                });

            modelBuilder.Entity("EFD2.Models.Employee", b =>
                {
                    b.HasOne("EFD2.Models.Department", "department")
                        .WithMany("Employees")
                        .HasForeignKey("did")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("department");
                });

            modelBuilder.Entity("EFD2.Models.empProj", b =>
                {
                    b.HasOne("EFD2.Models.Employee", "employee")
                        .WithMany("Projects")
                        .HasForeignKey("empid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EFD2.Models.Project", "project")
                        .WithMany("Employees")
                        .HasForeignKey("projid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("employee");

                    b.Navigation("project");
                });

            modelBuilder.Entity("EFD2.Models.Department", b =>
                {
                    b.Navigation("Employees");
                });

            modelBuilder.Entity("EFD2.Models.Employee", b =>
                {
                    b.Navigation("Projects");
                });

            modelBuilder.Entity("EFD2.Models.Project", b =>
                {
                    b.Navigation("Employees");
                });
#pragma warning restore 612, 618
        }
    }
}
