// <auto-generated />
using System;
using EFday2Task;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EFday2Task.Migrations
{
    [DbContext(typeof(NewsDBContext))]
    [Migration("20250515072455_v1")]
    partial class v1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EFday2Task.Models.Author", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Authors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "ali@gmial.com",
                            Name = "Ali Ashraf"
                        },
                        new
                        {
                            Id = 2,
                            Email = "omar@yahoo.com",
                            Name = "Omar Ahmed"
                        },
                        new
                        {
                            Id = 3,
                            Email = "mona@outlook.com",
                            Name = "Mona Ali"
                        });
                });

            modelBuilder.Entity("EFday2Task.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Government, elections, policies",
                            Name = "Politics"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Law, police, investigations",
                            Name = "Crime"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Games, athletes, competitions",
                            Name = "Sports"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Innovations, gadgets, AI",
                            Name = "Technology"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Markets, money, companies",
                            Name = "Economy"
                        });
                });

            modelBuilder.Entity("EFday2Task.Models.News", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AuthorId")
                        .HasColumnType("int");

                    b.Property<string>("Brief")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("PublishDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("CategoryId");

                    b.ToTable("News");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AuthorId = 2,
                            CategoryId = 5,
                            Title = "title1"
                        },
                        new
                        {
                            Id = 2,
                            AuthorId = 2,
                            CategoryId = 3,
                            Title = "title2"
                        },
                        new
                        {
                            Id = 3,
                            AuthorId = 1,
                            CategoryId = 4,
                            Title = "title3"
                        },
                        new
                        {
                            Id = 4,
                            AuthorId = 2,
                            CategoryId = 1,
                            Title = "title4"
                        },
                        new
                        {
                            Id = 5,
                            AuthorId = 3,
                            CategoryId = 4,
                            Title = "title5"
                        });
                });

            modelBuilder.Entity("EFday2Task.Models.News", b =>
                {
                    b.HasOne("EFday2Task.Models.Author", "Author")
                        .WithMany("News")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EFday2Task.Models.Category", "Category")
                        .WithMany("News")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("EFday2Task.Models.Author", b =>
                {
                    b.Navigation("News");
                });

            modelBuilder.Entity("EFday2Task.Models.Category", b =>
                {
                    b.Navigation("News");
                });
#pragma warning restore 612, 618
        }
    }
}
